#!/bin/sh
# Xcode Cloud: runs after the repository is cloned (Apple looks for ci_scripts/
# next to the .xcodeproj). The real bundle prefix and team are not in Git
# (AGENTS.md §2, D-101), so this writes the git-ignored Apple/Config/Local.xcconfig
# the same way a developer's Mac has it. Values, in order of preference:
#
#   bundle prefix:  TAMAGO_BUNDLE_PREFIX (workflow variable), else CI_BUNDLE_ID —
#                   Xcode Cloud's bundle ID of the product, which for TamagoPhone
#                   IS the prefix (PRODUCT_BUNDLE_IDENTIFIER = $(TAMAGO_BUNDLE_PREFIX)).
#   team:           TAMAGO_TEAM_ID, else CI_TEAM_ID; if neither, DEVELOPMENT_TEAM is
#                   left out and Xcode Cloud's managed signing picks the product's team.
#
# Nothing is printed except what was written.
set -eu

CONFIG_DIR="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/../.." && pwd)}/Apple/Config"
PREFIX="${TAMAGO_BUNDLE_PREFIX:-${CI_BUNDLE_ID:-}}"
TEAM="${TAMAGO_TEAM_ID:-${CI_TEAM_ID:-}}"

if [ -z "$PREFIX" ]; then
  echo "ci_post_clone: no bundle prefix (set TAMAGO_BUNDLE_PREFIX, or run under Xcode Cloud where CI_BUNDLE_ID exists)." >&2
  exit 1
fi

{
  echo "// Generated by ci_scripts/ci_post_clone.sh for Xcode Cloud. Not committed."
  echo "TAMAGO_BUNDLE_PREFIX = $PREFIX"
  [ -n "$TEAM" ] && echo "DEVELOPMENT_TEAM = $TEAM"
  echo "CODE_SIGN_STYLE = Automatic"
} > "$CONFIG_DIR/Local.xcconfig"

if [ -n "$TEAM" ]; then note="team set"; else note="team left to Xcode Cloud signing"; fi
echo "ci_post_clone: wrote Apple/Config/Local.xcconfig ($note)"
