#!/bin/sh
# Xcode Cloud: runs after the repository is cloned (Apple looks for ci_scripts/
# next to the .xcodeproj). The real bundle prefix and team are not in Git
# (AGENTS.md §2, D-101); they come from the workflow's environment variables:
#
#   TAMAGO_BUNDLE_PREFIX   e.g. com.yourname.tamawatch   (set in the workflow)
#   TAMAGO_TEAM_ID         your 10-character team ID      (set in the workflow)
#
# and are written to the git-ignored Apple/Config/Local.xcconfig, exactly as on
# a developer's Mac. Nothing is printed except whether the file was written.
set -eu

CONFIG_DIR="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/../.." && pwd)}/Apple/Config"

if [ -z "${TAMAGO_BUNDLE_PREFIX:-}" ] || [ -z "${TAMAGO_TEAM_ID:-}" ]; then
  echo "ci_post_clone: TAMAGO_BUNDLE_PREFIX and TAMAGO_TEAM_ID must be set in the Xcode Cloud workflow's environment." >&2
  exit 1
fi

cat > "$CONFIG_DIR/Local.xcconfig" <<XCCONFIG
// Generated by ci_scripts/ci_post_clone.sh for Xcode Cloud. Not committed.
TAMAGO_BUNDLE_PREFIX = ${TAMAGO_BUNDLE_PREFIX}
DEVELOPMENT_TEAM = ${TAMAGO_TEAM_ID}
CODE_SIGN_STYLE = Automatic
XCCONFIG

echo "ci_post_clone: wrote Apple/Config/Local.xcconfig"
